---
- name: Configure secret information
  hosts: webservers
  serial: 1
  tasks:
  - name: Read secrets from vault file
    include_vars:
      file: vault.yml
      name: secret_data
  - name: retrieved passwords
    debug:
      msg: "{{ secret_data }}"

  - name: Create secret.html
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
    template:
      dest: /var/www/html/secret.html
      src: secret.html.j2
      mode: 0666
